# Generated by Django 4.2.2 on 2023-08-12 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0003_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='dist',
            new_name='district',
        ),
    ]
