# Generated by Django 4.2.2 on 2023-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankingapp', '0004_rename_dist_branch_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phoneno',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
